# Generated by Django 6.0.7 on 2026-08-07 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0002_department_student_id_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('designation', models.CharField(choices=[('LECTURER', 'Lecturer'), ('SENIOR_LECTURER', 'Senior Lecturer'), ('ASSISTANT_PROFESSOR', 'Assistant Professor'), ('ASSOCIATE_PROFESSOR', 'Associate Professor'), ('PROFESSOR', 'Professor')], max_length=30)),
                ('qualification', models.CharField(max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('joining_date', models.DateField()),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('office_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('office_room', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='instructors/')),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('RETIRED', 'Retired'), ('RESIGNED', 'Resigned')], default='ACTIVE', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instructors', to='departments.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Instructor',
                'verbose_name_plural': 'Instructors',
                'db_table': 'instructors',
                'ordering': ['employee_id'],
            },
        ),
    ]
