# Generated by Django 6.0.7 on 2026-08-02 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('semester', '0002_remove_semester_unique_semester_per_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('credit', models.DecimalField(decimal_places=1, max_digits=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='departments.department')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='semester.semester')),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
                'db_table': 'courses',
                'ordering': ['course_code'],
                'constraints': [models.UniqueConstraint(fields=('department', 'semester', 'course_code'), name='unique_course_per_department_semester')],
            },
        ),
    ]
