# Generated by Django 6.0.7 on 2026-08-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_rename_title_course_course_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['department__name', 'semester__year', 'course_code'], 'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
    ]
