# Generated by Django 6.0.7 on 2026-08-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_course_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('LAB', 'Lab')], default='REGULAR', max_length=10),
        ),
    ]
