# Generated by Django 6.0.7 on 2026-08-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='student_id_code',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
