# Generated by Django 6.0.7 on 2026-08-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_department_student_id_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='student_id_code',
            new_name='id_prefix',
        ),
    ]
