# Generated by Django 6.0.7 on 2026-08-09 07:07

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course_offering', '0001_initial'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=150)),
                ('assessment_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('PRESENTATION', 'Presentation'), ('MID', 'Mid'), ('FINAL', 'Final'), ('LAB_PERFORMANCE', 'Lab Performance'), ('LAB_VIVA', 'Lab Viva'), ('LAB_FINAL', 'Lab Final')], max_length=30)),
                ('maximum_marks', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='course_offering.courseoffering')),
            ],
            options={
                'verbose_name': 'Assessment',
                'verbose_name_plural': 'Assessments',
                'db_table': 'assessments',
                'ordering': ['assessment_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marks', to='assessment.assessment')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_marks', to='enrollments.enrollment')),
            ],
            options={
                'verbose_name': 'Assessment Mark',
                'verbose_name_plural': 'Assessment Marks',
                'db_table': 'assessment_marks',
                'ordering': ['assessment', 'enrollment'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'enrollment'), name='unique_assessment_enrollment')],
            },
        ),
    ]
