# Generated by Django 6.0.7 on 2026-09-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={},
        ),
        migrations.AlterModelTable(
            name='assessment',
            table=None,
        ),
    ]
