# Generated by Django 6.0.7 on 2026-08-02 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('SPRING', 'Spring'), ('SUMMER', 'Summer'), ('FALL', 'Fall')], max_length=20)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000)])),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
                'db_table': 'semesters',
                'ordering': ['-year', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'year'), name='unique_semester_per_year'), models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='semester_start_before_end')],
            },
        ),
    ]
