# Generated by Django 6.0.7 on 2026-08-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semester', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='semester',
            name='unique_semester_per_year',
        ),
        migrations.RemoveConstraint(
            model_name='semester',
            name='semester_start_before_end',
        ),
        migrations.AlterField(
            model_name='semester',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('name', 'year')},
        ),
    ]
